export const projectImages = {
  restaurant: [
    "/assets/restaurant/1.jpg",
    "/assets/restaurant/2.jpg",
    "/assets/restaurant/3.jpg",
    "/assets/restaurant/4.jpg",
    "/assets/restaurant/5.jpg",
    "/assets/restaurant/6.jpg",
    "/assets/restaurant/9.jpg",
    "/assets/restaurant/11.jpg",
    "/assets/restaurant/12.jpg",
    "/assets/restaurant/13.jpg",
    "/assets/restaurant/14.jpg",
    "/assets/restaurant/15.jpg",
    "/assets/restaurant/16.jpg",
    "/assets/restaurant/18.jpg",
    "/assets/restaurant/19.jpg",
    "/assets/restaurant/20.jpg",
  ],
  streetlights: [
    "/assets/streetlights/1.jpg",
    "/assets/streetlights/2.jpg",
    "/assets/streetlights/3.jpg",
    "/assets/streetlights/4.jpg",
    "/assets/streetlights/5.jpg",
    "/assets/streetlights/6.jpg",
    "/assets/streetlights/7.jpg",
    "/assets/streetlights/8.jpg",
    "/assets/streetlights/9.jpg",
    "/assets/streetlights/10.jpg",
    "/assets/streetlights/11.jpg",
    "/assets/streetlights/12.jpg",
    "/assets/streetlights/13.jpg",
    "/assets/streetlights/14.jpg",
  ],
  bht: ["/assets/bht/1.png"],
  imagesqueeze: ["/assets/imagesqueeze/1.jpg", "/assets/imagesqueeze/2.jpg"],
  scraper: ["/assets/scraper/1.png", "/assets/scraper/2.png"],
};
